version: "3.7"
services:
    doccano:
        image: doccano/doccano
        container_name: doccano
        environment:
            ADMIN_USERNAME: "admin"
            ADMIN_PASSWORD: "password"
            ADMIN_EMAIL: "admin@example.com"
        ports:
            - 8000:8000

    huggingface-server:
        build: ./huggingface-server
        container_name: huggingface-server
        environment:
            HUGGINGFACE_USER: ${HUGGINGFACE_USER}
            HUGGINGFACE_PASSWORD: ${HUGGINGFACE_PASSWORD}
        ports:
            - 8080:8080
        depends_on:
            - doccano
